-- =====================================================================
-- QUICK DATA VALIDATION - All Tables Record Counts
-- Run this for a fast overview of all generated data
-- =====================================================================

USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE UC3_CUSTOMER_COMPLAINTS;

SELECT '====== QUICK DATA VALIDATION ======' as VALIDATION;

-- All tables in one view with expected counts
SELECT 
    'CUSTOMER_DATA.ACCOUNT' as TABLE_NAME,
    COUNT(*) as ACTUAL_COUNT,
    '50,000' as EXPECTED_COUNT,
    CASE WHEN COUNT(*) >= 50000 THEN '✓ PASS' ELSE '✗ FAIL' END as STATUS
FROM UC3_CUSTOMER_COMPLAINTS.CUSTOMER_DATA.ACCOUNT

UNION ALL

SELECT 
    'CUSTOMER_DATA.CONTACT',
    COUNT(*),
    '75,000',
    CASE WHEN COUNT(*) >= 75000 THEN '✓ PASS' ELSE '✗ FAIL' END
FROM UC3_CUSTOMER_COMPLAINTS.CUSTOMER_DATA.CONTACT

UNION ALL

SELECT 
    'CUSTOMER_DATA.CASE',
    COUNT(*),
    '15,000',
    CASE WHEN COUNT(*) >= 15000 THEN '✓ PASS' ELSE '✗ FAIL' END
FROM UC3_CUSTOMER_COMPLAINTS.CUSTOMER_DATA.CASE

UNION ALL

SELECT 
    'CUSTOMER_DATA.CASE_COMMENT',
    COUNT(*),
    '~45,000',
    CASE WHEN COUNT(*) >= 40000 THEN '✓ PASS' ELSE '✗ FAIL' END
FROM UC3_CUSTOMER_COMPLAINTS.CUSTOMER_DATA.CASE_COMMENT

UNION ALL

SELECT 
    'CUSTOMER_DATA.ASSET',
    COUNT(*),
    '100,000',
    CASE WHEN COUNT(*) >= 100000 THEN '✓ PASS' ELSE '✗ FAIL' END
FROM UC3_CUSTOMER_COMPLAINTS.CUSTOMER_DATA.ASSET

UNION ALL

SELECT 
    'CUSTOMER_DATA.SERVICE_CONTRACT',
    COUNT(*),
    '8,000',
    CASE WHEN COUNT(*) >= 8000 THEN '✓ PASS' ELSE '✗ FAIL' END
FROM UC3_CUSTOMER_COMPLAINTS.CUSTOMER_DATA.SERVICE_CONTRACT

UNION ALL

SELECT 
    'BILLING_DATA.CUSTOMER_MASTER',
    COUNT(*),
    '50,000',
    CASE WHEN COUNT(*) >= 50000 THEN '✓ PASS' ELSE '✗ FAIL' END
FROM UC3_CUSTOMER_COMPLAINTS.BILLING_DATA.CUSTOMER_MASTER

UNION ALL

SELECT 
    'BILLING_DATA.BILLING_ACCOUNT',
    COUNT(*),
    '50,000',
    CASE WHEN COUNT(*) >= 50000 THEN '✓ PASS' ELSE '✗ FAIL' END
FROM UC3_CUSTOMER_COMPLAINTS.BILLING_DATA.BILLING_ACCOUNT

UNION ALL

SELECT 
    'BILLING_DATA.SUBSCRIPTION',
    COUNT(*),
    '~125,000',
    CASE WHEN COUNT(*) >= 120000 THEN '✓ PASS' ELSE '✗ FAIL' END
FROM UC3_CUSTOMER_COMPLAINTS.BILLING_DATA.SUBSCRIPTION

UNION ALL

SELECT 
    'BILLING_DATA.BILL_INVOICE',
    COUNT(*),
    '300,000',
    CASE WHEN COUNT(*) >= 300000 THEN '✓ PASS' ELSE '✗ FAIL' END
FROM UC3_CUSTOMER_COMPLAINTS.BILLING_DATA.BILL_INVOICE

UNION ALL

SELECT 
    'BILLING_DATA.BILL_INVOICE_DETAIL',
    COUNT(*),
    '~900,000',
    CASE WHEN COUNT(*) >= 850000 THEN '✓ PASS' ELSE '✗ FAIL' END
FROM UC3_CUSTOMER_COMPLAINTS.BILLING_DATA.BILL_INVOICE_DETAIL

UNION ALL

SELECT 
    'BILLING_DATA.RATED_EVENTS',
    COUNT(*),
    '~1,200,000',
    CASE WHEN COUNT(*) >= 1000000 THEN '✓ PASS' ELSE '✗ FAIL' END
FROM UC3_CUSTOMER_COMPLAINTS.BILLING_DATA.RATED_EVENTS

UNION ALL

SELECT 
    'BILLING_DATA.PAYMENT',
    COUNT(*),
    '~270,000',
    CASE WHEN COUNT(*) >= 250000 THEN '✓ PASS' ELSE '✗ FAIL' END
FROM UC3_CUSTOMER_COMPLAINTS.BILLING_DATA.PAYMENT

UNION ALL

SELECT 
    'BILLING_DATA.DISPUTE',
    COUNT(*),
    '25,000',
    CASE WHEN COUNT(*) >= 25000 THEN '✓ PASS' ELSE '✗ FAIL' END
FROM UC3_CUSTOMER_COMPLAINTS.BILLING_DATA.DISPUTE

UNION ALL

SELECT 
    'BILLING_DATA.ADJUSTMENT',
    COUNT(*),
    '~50,000',
    CASE WHEN COUNT(*) >= 45000 THEN '✓ PASS' ELSE '✗ FAIL' END
FROM UC3_CUSTOMER_COMPLAINTS.BILLING_DATA.ADJUSTMENT

UNION ALL

SELECT 
    'COMPLAINTS.VOICE_TRANSCRIPT',
    COUNT(*),
    '1,000',
    CASE WHEN COUNT(*) >= 1000 THEN '✓ PASS' ELSE '✗ FAIL' END
FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.VOICE_TRANSCRIPT

UNION ALL

SELECT 
    'COMPLAINTS.EMAIL_COMPLAINT',
    COUNT(*),
    '5,000',
    CASE WHEN COUNT(*) >= 5000 THEN '✓ PASS' ELSE '✗ FAIL' END
FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.EMAIL_COMPLAINT

UNION ALL

SELECT 
    'COMPLAINTS.SOCIAL_MEDIA_POST',
    COUNT(*),
    '3,000',
    CASE WHEN COUNT(*) >= 3000 THEN '✓ PASS' ELSE '✗ FAIL' END
FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.SOCIAL_MEDIA_POST

UNION ALL

SELECT 
    'COMPLAINTS.CHAT_SESSION',
    COUNT(*),
    '8,000',
    CASE WHEN COUNT(*) >= 8000 THEN '✓ PASS' ELSE '✗ FAIL' END
FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.CHAT_SESSION

UNION ALL

SELECT 
    'COMPLAINTS.SURVEY_RESPONSE',
    COUNT(*),
    '12,000',
    CASE WHEN COUNT(*) >= 12000 THEN '✓ PASS' ELSE '✗ FAIL' END
FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.SURVEY_RESPONSE

UNION ALL

SELECT 
    'COMPLAINTS.UNIFIED_COMPLAINT',
    COUNT(*),
    '~20,000+',
    CASE WHEN COUNT(*) >= 15000 THEN '✓ PASS' ELSE '✗ FAIL' END
FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.UNIFIED_COMPLAINT

ORDER BY TABLE_NAME;

-- Overall Status
SELECT 
    '====== OVERALL STATUS ======' as STATUS_HEADER,
    (SELECT COUNT(*) FROM UC3_CUSTOMER_COMPLAINTS.CUSTOMER_DATA.ACCOUNT) as ACCOUNTS,
    (SELECT COUNT(*) FROM UC3_CUSTOMER_COMPLAINTS.BILLING_DATA.CUSTOMER_MASTER) as CUSTOMERS,
    (SELECT COUNT(*) FROM UC3_CUSTOMER_COMPLAINTS.BILLING_DATA.BILL_INVOICE) as INVOICES,
    (SELECT COUNT(*) FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.VOICE_TRANSCRIPT) as VOICE,
    (SELECT COUNT(*) FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.EMAIL_COMPLAINT) as EMAIL,
    (SELECT COUNT(*) FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.SOCIAL_MEDIA_POST) as SOCIAL,
    (SELECT COUNT(*) FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.CHAT_SESSION) as CHAT,
    (SELECT COUNT(*) FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.SURVEY_RESPONSE) as SURVEY,
    (SELECT COUNT(*) FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.UNIFIED_COMPLAINT) as UNIFIED;

SELECT 
    '====== DATA GENERATION COMPLETE ======' as RESULT,
    'All tables populated successfully!' as MESSAGE;
