-- =====================================================================
-- UC3 - Customer Complaints & Sentiment Analysis Platform
-- Database Setup Script
-- =====================================================================
-- Purpose: Create database, schemas, tables, views, and procedures
-- Execution: Run in Snowflake UI (Worksheets) with "Run All"
-- Time: ~2-3 minutes
-- =====================================================================

-- Set role and warehouse
USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;

-- =====================================================================
-- SECTION 1: DATABASE AND SCHEMA CREATION
-- =====================================================================

-- Create main database
CREATE DATABASE IF NOT EXISTS UC3_CUSTOMER_COMPLAINTS
    COMMENT = 'UC3 - Customer Complaints & Sentiment Analysis Platform';

USE DATABASE UC3_CUSTOMER_COMPLAINTS;

-- Create schemas
CREATE SCHEMA IF NOT EXISTS CUSTOMER_DATA
    COMMENT = 'CRM system objects - accounts, contacts, cases';

CREATE SCHEMA IF NOT EXISTS BILLING_DATA
    COMMENT = 'Billing system objects - invoices, payments, disputes';

CREATE SCHEMA IF NOT EXISTS COMPLAINTS
    COMMENT = 'Multi-channel complaint data - voice, email, social, chat, survey';

CREATE SCHEMA IF NOT EXISTS SENTIMENT
    COMMENT = 'AI analysis results - sentiment scores, emotion detection, topic classification';

CREATE SCHEMA IF NOT EXISTS ANALYTICS
    COMMENT = 'Analytics views and KPIs';

CREATE SCHEMA IF NOT EXISTS STAGING
    COMMENT = 'Staging area for data loading';

CREATE SCHEMA IF NOT EXISTS INTEGRATION
    COMMENT = 'Integration with UC2 network data';

-- =====================================================================
-- SECTION 2: FILE FORMAT AND STAGE (for CSV uploads)
-- =====================================================================

USE SCHEMA STAGING;

-- Create file format for CSV files
CREATE OR REPLACE FILE FORMAT CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    RECORD_DELIMITER = '\n'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    TRIM_SPACE = TRUE
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
    ESCAPE = 'NONE'
    ESCAPE_UNENCLOSED_FIELD = '\134'
    DATE_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
    NULL_IF = ('NULL', 'null', '', 'N/A');

-- Create JSON file format for voice transcripts
CREATE OR REPLACE FILE FORMAT JSON_FORMAT
    TYPE = 'JSON'
    STRIP_OUTER_ARRAY = FALSE
    DATE_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO';

-- Create named stage for file uploads
CREATE OR REPLACE STAGE CSV_DATA
    FILE_FORMAT = CSV_FORMAT
    COMMENT = 'Stage for uploading CSV data files';

CREATE OR REPLACE STAGE JSON_DATA
    FILE_FORMAT = JSON_FORMAT
    COMMENT = 'Stage for uploading JSON voice transcript files';

-- =====================================================================
-- SECTION 3: CUSTOMER_DATA SCHEMA - CRM SYSTEM TABLES
-- =====================================================================

USE SCHEMA CUSTOMER_DATA;

-- ACCOUNT: Master customer records
CREATE OR REPLACE TABLE ACCOUNT (
    ACCOUNT_ID VARCHAR(50) PRIMARY KEY,
    ACCOUNT_NUMBER VARCHAR(50) UNIQUE NOT NULL,
    ACCOUNT_NAME VARCHAR(200) NOT NULL,
    ACCOUNT_TYPE VARCHAR(20) NOT NULL, -- residential, business, enterprise
    STATUS VARCHAR(20) NOT NULL, -- active, suspended, closed
    TIER VARCHAR(20), -- gold, silver, bronze
    PRIMARY_SITE_ID VARCHAR(50), -- LINKS to UC2.DIM_CELL_SITE
    REGION VARCHAR(50),
    DISTRICT VARCHAR(100),
    CITY VARCHAR(100),
    ADDRESS_LINE1 VARCHAR(200),
    ADDRESS_LINE2 VARCHAR(200),
    POSTAL_CODE VARCHAR(20),
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    CREATED_DATE DATE NOT NULL,
    CUSTOMER_SINCE DATE NOT NULL,
    LAST_MODIFIED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY VARCHAR(100),
    MODIFIED_BY VARCHAR(100)
) COMMENT = 'Customer accounts - synchronized with UC2 network sites';

-- CONTACT: Individual contacts
CREATE OR REPLACE TABLE CONTACT (
    CONTACT_ID VARCHAR(50) PRIMARY KEY,
    ACCOUNT_ID VARCHAR(50) NOT NULL,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    FULL_NAME VARCHAR(200),
    EMAIL VARCHAR(200),
    PHONE VARCHAR(50),
    MOBILE_PHONE VARCHAR(50),
    PREFERRED_CONTACT_METHOD VARCHAR(20), -- phone, email, sms
    LANGUAGE_PREFERENCE VARCHAR(10) DEFAULT 'PT', -- PT, EN
    IS_PRIMARY BOOLEAN DEFAULT FALSE,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID)
) COMMENT = 'Individual customer contacts';

-- CASE: Customer complaints and support tickets
CREATE OR REPLACE TABLE CASE (
    CASE_ID VARCHAR(50) PRIMARY KEY,
    CASE_NUMBER VARCHAR(50) UNIQUE NOT NULL,
    ACCOUNT_ID VARCHAR(50) NOT NULL,
    CONTACT_ID VARCHAR(50),
    SUBJECT VARCHAR(500),
    DESCRIPTION TEXT,
    CATEGORY VARCHAR(100), -- network_outage, billing_dispute, technical_support, etc.
    SUBCATEGORY VARCHAR(100),
    PRIORITY VARCHAR(20), -- critical, high, medium, low
    STATUS VARCHAR(20), -- new, open, in_progress, resolved, closed
    CHANNEL VARCHAR(20), -- voice, email, social, chat, web
    ORIGIN VARCHAR(50), -- call_center, web_portal, mobile_app, social_media
    NETWORK_INCIDENT_ID VARCHAR(50), -- LINKS to UC2.FACT_INCIDENTS
    AFFECTED_SERVICE_TYPE VARCHAR(100),
    OWNER_ID VARCHAR(50), -- agent assigned
    CREATED_DATE TIMESTAMP_NTZ NOT NULL,
    CLOSED_DATE TIMESTAMP_NTZ,
    FIRST_RESPONSE_TIME_MINUTES INT,
    RESOLUTION_TIME_MINUTES INT,
    ESCALATED BOOLEAN DEFAULT FALSE,
    ESCALATION_DATE TIMESTAMP_NTZ,
    SATISFACTION_SCORE INT, -- 1-5
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID)
) COMMENT = 'Customer complaints and support cases - linked to UC2 incidents';

-- CASE_COMMENT: Case interactions and updates
CREATE OR REPLACE TABLE CASE_COMMENT (
    COMMENT_ID VARCHAR(50) PRIMARY KEY,
    CASE_ID VARCHAR(50) NOT NULL,
    PARENT_COMMENT_ID VARCHAR(50),
    COMMENT_TEXT TEXT NOT NULL,
    CREATED_BY VARCHAR(100) NOT NULL,
    CREATED_BY_TYPE VARCHAR(20), -- agent, system, customer
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_PUBLIC BOOLEAN DEFAULT TRUE,
    COMMENT_TYPE VARCHAR(50), -- note, resolution, escalation, update
    FOREIGN KEY (CASE_ID) REFERENCES CASE(CASE_ID)
) COMMENT = 'Case interactions and communication history';

-- ASSET: Products and services owned by customer
CREATE OR REPLACE TABLE ASSET (
    ASSET_ID VARCHAR(50) PRIMARY KEY,
    ACCOUNT_ID VARCHAR(50) NOT NULL,
    ASSET_NAME VARCHAR(200),
    PRODUCT_NAME VARCHAR(200) NOT NULL,
    PRODUCT_CATEGORY VARCHAR(100), -- mobile, internet, tv, equipment
    PRODUCT_CODE VARCHAR(50),
    SERIAL_NUMBER VARCHAR(100),
    STATUS VARCHAR(20), -- active, suspended, deactivated
    INSTALLATION_DATE DATE,
    ACTIVATION_DATE DATE,
    DEACTIVATION_DATE DATE,
    SERVING_SITE_ID VARCHAR(50), -- LINKS to UC2.DIM_CELL_SITE
    WARRANTY_END_DATE DATE,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID)
) COMMENT = 'Customer assets - products and services';

-- SERVICE_CONTRACT: Service level agreements
CREATE OR REPLACE TABLE SERVICE_CONTRACT (
    CONTRACT_ID VARCHAR(50) PRIMARY KEY,
    ACCOUNT_ID VARCHAR(50) NOT NULL,
    CONTRACT_NUMBER VARCHAR(50) UNIQUE NOT NULL,
    CONTRACT_TYPE VARCHAR(100), -- standard, premium, enterprise
    CONTRACT_NAME VARCHAR(200),
    START_DATE DATE NOT NULL,
    END_DATE DATE,
    STATUS VARCHAR(20), -- active, expired, cancelled
    SLA_LEVEL VARCHAR(50), -- gold_24x7, silver_business_hours, bronze_best_effort
    RESPONSE_TIME_HOURS INT,
    RESOLUTION_TIME_HOURS INT,
    MONTHLY_VALUE DECIMAL(15,2),
    ANNUAL_VALUE DECIMAL(15,2),
    AUTO_RENEW BOOLEAN DEFAULT FALSE,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID)
) COMMENT = 'Service contracts and SLA agreements';

-- =====================================================================
-- SECTION 4: BILLING_DATA SCHEMA - BILLING SYSTEM TABLES
-- =====================================================================

USE SCHEMA BILLING_DATA;

-- CUSTOMER_MASTER: Master customer billing record
CREATE OR REPLACE TABLE CUSTOMER_MASTER (
    CUSTOMER_ID VARCHAR(50) PRIMARY KEY,
    ACCOUNT_ID VARCHAR(50) NOT NULL, -- SYNCED with CUSTOMER_DATA.ACCOUNT
    BILLING_CYCLE INT, -- day of month: 1, 5, 10, 15, 20, 25
    PAYMENT_METHOD VARCHAR(50), -- direct_debit, credit_card, bank_transfer, multibanco
    CREDIT_CLASS VARCHAR(20), -- A, B, C, D
    CREDIT_LIMIT DECIMAL(15,2),
    STATUS VARCHAR(20), -- active, suspended, collections
    REGION VARCHAR(50),
    CURRENCY VARCHAR(3) DEFAULT 'EUR',
    TAX_ID VARCHAR(50),
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'Master billing customer records';

-- BILLING_ACCOUNT: Billing accounts (can have multiple per customer)
CREATE OR REPLACE TABLE BILLING_ACCOUNT (
    BILLING_ACCOUNT_ID VARCHAR(50) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(50) NOT NULL,
    ACCOUNT_NUMBER VARCHAR(50) UNIQUE NOT NULL,
    ACCOUNT_TYPE VARCHAR(50), -- postpaid, prepaid, hybrid
    ACCOUNT_NAME VARCHAR(200),
    BALANCE DECIMAL(15,2) DEFAULT 0.00,
    CREDIT_LIMIT DECIMAL(15,2),
    STATUS VARCHAR(20), -- active, suspended, collections, closed
    CURRENCY VARCHAR(3) DEFAULT 'EUR',
    BILLING_CYCLE INT,
    BILL_DELIVERY_METHOD VARCHAR(20), -- email, postal, portal
    CREATED_DATE DATE NOT NULL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER_MASTER(CUSTOMER_ID)
) COMMENT = 'Billing accounts - can be multiple per customer';

-- SUBSCRIPTION: Active services and subscriptions
CREATE OR REPLACE TABLE SUBSCRIPTION (
    SUBSCRIPTION_ID VARCHAR(50) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(50) NOT NULL,
    BILLING_ACCOUNT_ID VARCHAR(50) NOT NULL,
    SERVICE_TYPE VARCHAR(50), -- mobile, internet, tv, bundle
    PACKAGE_ID VARCHAR(50),
    PACKAGE_NAME VARCHAR(200),
    MONTHLY_CHARGE DECIMAL(15,2) NOT NULL,
    ACTIVATION_DATE DATE NOT NULL,
    DEACTIVATION_DATE DATE,
    STATUS VARCHAR(20), -- active, suspended, cancelled
    CONTRACT_TERM_MONTHS INT,
    CONTRACT_END_DATE DATE,
    AUTO_RENEW BOOLEAN DEFAULT FALSE,
    SERVING_SITE_ID VARCHAR(50), -- LINKS to UC2.DIM_CELL_SITE
    PHONE_NUMBER VARCHAR(50),
    DATA_ALLOWANCE_GB INT,
    VOICE_MINUTES INT,
    SMS_ALLOWANCE INT,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER_MASTER(CUSTOMER_ID),
    FOREIGN KEY (BILLING_ACCOUNT_ID) REFERENCES BILLING_ACCOUNT(BILLING_ACCOUNT_ID)
) COMMENT = 'Customer subscriptions - linked to UC2 serving sites';

-- PACKAGE: Service package definitions
CREATE OR REPLACE TABLE PACKAGE (
    PACKAGE_ID VARCHAR(50) PRIMARY KEY,
    PACKAGE_NAME VARCHAR(200) NOT NULL,
    PACKAGE_CODE VARCHAR(50) UNIQUE,
    SERVICE_CATEGORY VARCHAR(50), -- mobile, internet, tv, bundle
    MONTHLY_PRICE DECIMAL(15,2) NOT NULL,
    DATA_ALLOWANCE_GB INT,
    VOICE_MINUTES INT,
    SMS_ALLOWANCE INT,
    DOWNLOAD_SPEED_MBPS INT,
    UPLOAD_SPEED_MBPS INT,
    TV_CHANNELS_COUNT INT,
    FEATURES TEXT,
    STATUS VARCHAR(20), -- active, deprecated
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'Service package catalog';

-- BILL_INVOICE: Monthly invoices
CREATE OR REPLACE TABLE BILL_INVOICE (
    INVOICE_ID VARCHAR(50) PRIMARY KEY,
    BILLING_ACCOUNT_ID VARCHAR(50) NOT NULL,
    INVOICE_NUMBER VARCHAR(50) UNIQUE NOT NULL,
    INVOICE_DATE DATE NOT NULL,
    DUE_DATE DATE NOT NULL,
    BILLING_PERIOD_START DATE NOT NULL,
    BILLING_PERIOD_END DATE NOT NULL,
    SUBTOTAL_AMOUNT DECIMAL(15,2) NOT NULL,
    TAX_AMOUNT DECIMAL(15,2) NOT NULL,
    TOTAL_AMOUNT DECIMAL(15,2) NOT NULL,
    AMOUNT_PAID DECIMAL(15,2) DEFAULT 0.00,
    BALANCE DECIMAL(15,2),
    STATUS VARCHAR(20), -- pending, paid, overdue, disputed, cancelled
    PAYMENT_RECEIVED_DATE DATE,
    CURRENCY VARCHAR(3) DEFAULT 'EUR',
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (BILLING_ACCOUNT_ID) REFERENCES BILLING_ACCOUNT(BILLING_ACCOUNT_ID)
) COMMENT = 'Monthly billing invoices';

-- BILL_INVOICE_DETAIL: Invoice line items
CREATE OR REPLACE TABLE BILL_INVOICE_DETAIL (
    DETAIL_ID VARCHAR(50) PRIMARY KEY,
    INVOICE_ID VARCHAR(50) NOT NULL,
    LINE_NUMBER INT NOT NULL,
    CHARGE_TYPE VARCHAR(50), -- subscription, usage, one_time, adjustment, tax
    DESCRIPTION VARCHAR(500),
    SUBSCRIPTION_ID VARCHAR(50),
    SERVICE_PERIOD_START DATE,
    SERVICE_PERIOD_END DATE,
    QUANTITY DECIMAL(15,4),
    UNIT_PRICE DECIMAL(15,4),
    AMOUNT DECIMAL(15,2) NOT NULL,
    TAX_AMOUNT DECIMAL(15,2),
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (INVOICE_ID) REFERENCES BILL_INVOICE(INVOICE_ID)
) COMMENT = 'Invoice line item details';

-- RATED_EVENTS: Usage events (calls, data, SMS)
CREATE OR REPLACE TABLE RATED_EVENTS (
    EVENT_ID VARCHAR(50) PRIMARY KEY,
    SUBSCRIPTION_ID VARCHAR(50) NOT NULL,
    EVENT_TYPE VARCHAR(20), -- voice, data, sms, mms
    EVENT_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    DURATION_SECONDS INT,
    VOLUME_MB DECIMAL(15,4),
    QUANTITY INT,
    DESTINATION VARCHAR(100),
    RATED_AMOUNT DECIMAL(15,4),
    SERVING_SITE_ID VARCHAR(50), -- LINKS to UC2.DIM_CELL_SITE
    ROAMING BOOLEAN DEFAULT FALSE,
    RATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (SUBSCRIPTION_ID) REFERENCES SUBSCRIPTION(SUBSCRIPTION_ID)
) COMMENT = 'Usage events - voice calls, data, SMS';

-- DISPUTE: Billing disputes
CREATE OR REPLACE TABLE DISPUTE (
    DISPUTE_ID VARCHAR(50) PRIMARY KEY,
    BILLING_ACCOUNT_ID VARCHAR(50) NOT NULL,
    INVOICE_ID VARCHAR(50),
    DISPUTE_NUMBER VARCHAR(50) UNIQUE NOT NULL,
    DISPUTE_AMOUNT DECIMAL(15,2) NOT NULL,
    DISPUTE_REASON TEXT NOT NULL,
    CATEGORY VARCHAR(100), -- incorrect_charge, service_interruption, unauthorized_charge, other
    OPENED_DATE DATE NOT NULL,
    RESOLVED_DATE DATE,
    STATUS VARCHAR(20), -- open, investigating, resolved, rejected, cancelled
    RESOLUTION_TYPE VARCHAR(50), -- credit_issued, charge_corrected, dispute_rejected, partial_credit
    ADJUSTMENT_GIVEN DECIMAL(15,2),
    NETWORK_INCIDENT_ID VARCHAR(50), -- LINKS to UC2 if related to outage
    ASSIGNED_TO VARCHAR(100),
    RESOLUTION_NOTES TEXT,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (BILLING_ACCOUNT_ID) REFERENCES BILLING_ACCOUNT(BILLING_ACCOUNT_ID)
) COMMENT = 'Billing disputes - linked to network incidents when applicable';

-- ADJUSTMENT: Credits and corrections
CREATE OR REPLACE TABLE ADJUSTMENT (
    ADJUSTMENT_ID VARCHAR(50) PRIMARY KEY,
    BILLING_ACCOUNT_ID VARCHAR(50) NOT NULL,
    INVOICE_ID VARCHAR(50),
    ADJUSTMENT_TYPE VARCHAR(50), -- credit, debit, correction
    AMOUNT DECIMAL(15,2) NOT NULL,
    REASON TEXT NOT NULL,
    REASON_CODE VARCHAR(50),
    NETWORK_INCIDENT_ID VARCHAR(50), -- LINKS to UC2 if related to outage
    APPLIED_DATE DATE NOT NULL,
    APPLIED_TO_INVOICE_ID VARCHAR(50),
    APPROVED_BY VARCHAR(100),
    APPROVAL_DATE TIMESTAMP_NTZ,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (BILLING_ACCOUNT_ID) REFERENCES BILLING_ACCOUNT(BILLING_ACCOUNT_ID)
) COMMENT = 'Billing adjustments, credits, and corrections';

-- PAYMENT: Payment transactions
CREATE OR REPLACE TABLE PAYMENT (
    PAYMENT_ID VARCHAR(50) PRIMARY KEY,
    BILLING_ACCOUNT_ID VARCHAR(50) NOT NULL,
    INVOICE_ID VARCHAR(50),
    PAYMENT_NUMBER VARCHAR(50) UNIQUE NOT NULL,
    PAYMENT_DATE DATE NOT NULL,
    AMOUNT DECIMAL(15,2) NOT NULL,
    PAYMENT_METHOD VARCHAR(50), -- direct_debit, credit_card, bank_transfer, multibanco, cash
    STATUS VARCHAR(20), -- successful, failed, pending, reversed
    TRANSACTION_REFERENCE VARCHAR(100),
    BANK_REFERENCE VARCHAR(100),
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (BILLING_ACCOUNT_ID) REFERENCES BILLING_ACCOUNT(BILLING_ACCOUNT_ID)
) COMMENT = 'Payment transactions';

-- AR_BALANCE: Accounts receivable balances
CREATE OR REPLACE TABLE AR_BALANCE (
    BALANCE_ID VARCHAR(50) PRIMARY KEY,
    BILLING_ACCOUNT_ID VARCHAR(50) UNIQUE NOT NULL,
    CURRENT_BALANCE DECIMAL(15,2) DEFAULT 0.00,
    OVERDUE_BALANCE DECIMAL(15,2) DEFAULT 0.00,
    AGING_0_30 DECIMAL(15,2) DEFAULT 0.00,
    AGING_31_60 DECIMAL(15,2) DEFAULT 0.00,
    AGING_61_90 DECIMAL(15,2) DEFAULT 0.00,
    AGING_91_PLUS DECIMAL(15,2) DEFAULT 0.00,
    LAST_PAYMENT_DATE DATE,
    LAST_PAYMENT_AMOUNT DECIMAL(15,2),
    LAST_INVOICE_DATE DATE,
    LAST_INVOICE_AMOUNT DECIMAL(15,2),
    AS_OF_DATE DATE NOT NULL,
    UPDATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (BILLING_ACCOUNT_ID) REFERENCES BILLING_ACCOUNT(BILLING_ACCOUNT_ID)
) COMMENT = 'Accounts receivable aging balances';

-- COLLECTION_QUEUE: Collections and dunning
CREATE OR REPLACE TABLE COLLECTION_QUEUE (
    QUEUE_ID VARCHAR(50) PRIMARY KEY,
    BILLING_ACCOUNT_ID VARCHAR(50) NOT NULL,
    COLLECTION_STAGE VARCHAR(50), -- reminder, warning, final_notice, collections, legal
    TOTAL_DUE DECIMAL(15,2) NOT NULL,
    DAYS_OVERDUE INT NOT NULL,
    LAST_ACTION_DATE DATE,
    LAST_ACTION_TYPE VARCHAR(50), -- email_sent, sms_sent, call_made, letter_sent
    NEXT_ACTION_DATE DATE,
    NEXT_ACTION_TYPE VARCHAR(50),
    ASSIGNED_TO VARCHAR(100),
    NOTES TEXT,
    STATUS VARCHAR(20), -- active, on_hold, resolved, escalated
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (BILLING_ACCOUNT_ID) REFERENCES BILLING_ACCOUNT(BILLING_ACCOUNT_ID)
) COMMENT = 'Collections and dunning queue';

-- =====================================================================
-- SECTION 5: COMPLAINTS SCHEMA - MULTI-CHANNEL COMPLAINT DATA
-- =====================================================================

USE SCHEMA COMPLAINTS;

-- VOICE_TRANSCRIPT: Call center recordings (TEXT format)
CREATE OR REPLACE TABLE VOICE_TRANSCRIPT (
    TRANSCRIPT_ID VARCHAR(50) PRIMARY KEY,
    CALL_ID VARCHAR(50) UNIQUE NOT NULL,
    CASE_ID VARCHAR(50),
    CUSTOMER_ID VARCHAR(50) NOT NULL,
    ACCOUNT_ID VARCHAR(50),
    CALL_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    DURATION_SECONDS INT NOT NULL,
    AGENT_ID VARCHAR(50),
    AGENT_NAME VARCHAR(200),
    QUEUE_NAME VARCHAR(100),
    TRANSCRIPT_TEXT TEXT, -- Full conversation text
    TRANSCRIPT_JSON VARIANT, -- Structured conversation with speaker/timestamp
    CALL_OUTCOME VARCHAR(100),
    RESOLUTION VARCHAR(500),
    ESCALATED BOOLEAN DEFAULT FALSE,
    FIRST_CALL_RESOLUTION BOOLEAN,
    CUSTOMER_SATISFACTION INT, -- 1-5
    NETWORK_INCIDENT_ID VARCHAR(50), -- LINKS to UC2 if outage-related
    SITE_ID VARCHAR(50), -- LINKS to UC2.DIM_CELL_SITE
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'Voice call transcripts - linked to UC2 incidents and sites';

-- VOICE_METADATA: Call statistics and metrics
CREATE OR REPLACE TABLE VOICE_METADATA (
    METADATA_ID VARCHAR(50) PRIMARY KEY,
    CALL_ID VARCHAR(50) UNIQUE NOT NULL,
    WAIT_TIME_SECONDS INT,
    HANDLE_TIME_SECONDS INT,
    HOLD_TIME_SECONDS INT,
    AFTER_CALL_WORK_SECONDS INT,
    TRANSFERS_COUNT INT DEFAULT 0,
    CONFERENCE_COUNT INT DEFAULT 0,
    MUTE_TIME_SECONDS INT,
    CUSTOMER_SATISFACTION_SCORE INT, -- 1-5
    FIRST_CALL_RESOLUTION BOOLEAN,
    CALL_RECORDING_URL VARCHAR(500),
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (CALL_ID) REFERENCES VOICE_TRANSCRIPT(CALL_ID)
) COMMENT = 'Voice call statistics and KPIs';

-- EMAIL_COMPLAINT: Email correspondence
CREATE OR REPLACE TABLE EMAIL_COMPLAINT (
    EMAIL_ID VARCHAR(50) PRIMARY KEY,
    CASE_ID VARCHAR(50),
    CUSTOMER_ID VARCHAR(50) NOT NULL,
    FROM_ADDRESS VARCHAR(200) NOT NULL,
    TO_ADDRESS VARCHAR(200),
    CC_ADDRESSES VARCHAR(500),
    SUBJECT VARCHAR(500),
    BODY_TEXT TEXT,
    BODY_HTML TEXT,
    RECEIVED_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    REPLIED_TIMESTAMP TIMESTAMP_NTZ,
    CATEGORY VARCHAR(100),
    PRIORITY VARCHAR(20),
    ATTACHMENTS_COUNT INT DEFAULT 0,
    IS_REPLIED BOOLEAN DEFAULT FALSE,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'Email complaints and correspondence';

-- SOCIAL_MEDIA_POST: Social media mentions and complaints
CREATE OR REPLACE TABLE SOCIAL_MEDIA_POST (
    POST_ID VARCHAR(50) PRIMARY KEY,
    CASE_ID VARCHAR(50),
    PLATFORM VARCHAR(50), -- twitter, facebook, instagram, linkedin
    CUSTOMER_ID VARCHAR(50),
    USERNAME VARCHAR(100),
    POST_TEXT TEXT NOT NULL,
    POST_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    POST_URL VARCHAR(500),
    PUBLIC_REPLY TEXT,
    REPLY_TIMESTAMP TIMESTAMP_NTZ,
    ENGAGEMENT_COUNT INT DEFAULT 0, -- likes, shares, comments
    RETWEET_COUNT INT DEFAULT 0,
    HASHTAGS VARCHAR(500),
    MENTIONS VARCHAR(500),
    INFLUENCER_FLAG BOOLEAN DEFAULT FALSE,
    FOLLOWER_COUNT INT,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'Social media posts and complaints';

-- CHAT_SESSION: Live chat logs
CREATE OR REPLACE TABLE CHAT_SESSION (
    SESSION_ID VARCHAR(50) PRIMARY KEY,
    CASE_ID VARCHAR(50),
    CUSTOMER_ID VARCHAR(50) NOT NULL,
    AGENT_ID VARCHAR(50),
    AGENT_NAME VARCHAR(200),
    START_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    END_TIMESTAMP TIMESTAMP_NTZ,
    DURATION_SECONDS INT,
    TRANSCRIPT_TEXT TEXT, -- Full chat log
    TRANSCRIPT_JSON VARIANT, -- Structured chat with speaker/timestamp
    MESSAGES_COUNT INT,
    WAIT_TIME_SECONDS INT,
    SATISFACTION_RATING INT, -- 1-5
    RESOLUTION VARCHAR(500),
    ESCALATED BOOLEAN DEFAULT FALSE,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'Live chat session transcripts';

-- SURVEY_RESPONSE: NPS, CSAT, and feedback surveys
CREATE OR REPLACE TABLE SURVEY_RESPONSE (
    RESPONSE_ID VARCHAR(50) PRIMARY KEY,
    SURVEY_TYPE VARCHAR(50), -- nps, csat, ces, general_feedback
    CUSTOMER_ID VARCHAR(50) NOT NULL,
    CASE_ID VARCHAR(50),
    INTERACTION_ID VARCHAR(50),
    SURVEY_NAME VARCHAR(200),
    SCORE INT, -- NPS: 0-10, CSAT: 1-5, CES: 1-7
    COMMENT_TEXT TEXT,
    RESPONSE_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    SURVEY_SENT_DATE DATE,
    CHANNEL VARCHAR(50), -- email, sms, web, app
    PROMOTER_CATEGORY VARCHAR(20), -- promoter, passive, detractor (for NPS)
    QUESTION_RESPONSES VARIANT, -- JSON with all Q&A
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'Customer satisfaction surveys - NPS, CSAT, CES';

-- UNIFIED_COMPLAINT: All channels combined and normalized
CREATE OR REPLACE TABLE UNIFIED_COMPLAINT (
    COMPLAINT_ID VARCHAR(50) PRIMARY KEY,
    CASE_ID VARCHAR(50),
    CUSTOMER_ID VARCHAR(50) NOT NULL,
    ACCOUNT_ID VARCHAR(50),
    CHANNEL VARCHAR(20) NOT NULL, -- voice, email, social, chat, survey
    SOURCE_ID VARCHAR(50), -- ID from source table (call_id, email_id, etc.)
    COMPLAINT_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    COMPLAINT_TEXT TEXT NOT NULL, -- Normalized complaint text
    CATEGORY VARCHAR(100),
    SUBCATEGORY VARCHAR(100),
    PRIORITY VARCHAR(20),
    STATUS VARCHAR(20),
    NETWORK_INCIDENT_ID VARCHAR(50), -- LINKS to UC2.FACT_INCIDENTS
    BILLING_DISPUTE_ID VARCHAR(50), -- LINKS to BILLING_DATA.DISPUTE
    RESOLVED BOOLEAN DEFAULT FALSE,
    RESOLUTION_DATE TIMESTAMP_NTZ,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'Unified view of all complaints across channels';

-- =====================================================================
-- SECTION 6: SENTIMENT SCHEMA - AI ANALYSIS RESULTS
-- =====================================================================

USE SCHEMA SENTIMENT;

-- SENTIMENT_SCORE: Cortex AI sentiment analysis results
CREATE OR REPLACE TABLE SENTIMENT_SCORE (
    SENTIMENT_ID VARCHAR(50) PRIMARY KEY,
    COMPLAINT_ID VARCHAR(50) UNIQUE NOT NULL,
    OVERALL_SENTIMENT VARCHAR(20), -- positive, negative, neutral
    SENTIMENT_SCORE FLOAT, -- -1.0 to 1.0
    CONFIDENCE_LEVEL FLOAT, -- 0.0 to 1.0
    ANALYZED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    MODEL_VERSION VARCHAR(50),
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'Sentiment analysis results from Snowflake Cortex AI';

-- EMOTION_DETECTION: Emotion classification
CREATE OR REPLACE TABLE EMOTION_DETECTION (
    EMOTION_ID VARCHAR(50) PRIMARY KEY,
    COMPLAINT_ID VARCHAR(50) NOT NULL,
    PRIMARY_EMOTION VARCHAR(50), -- angry, frustrated, satisfied, confused, neutral
    EMOTION_INTENSITY INT, -- 0-100
    SECONDARY_EMOTIONS VARCHAR(500), -- JSON array
    EMOTION_TIMELINE VARIANT, -- For voice: emotion changes during call
    ANALYZED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'Emotion detection and classification';

-- TOPIC_CLASSIFICATION: Root cause categorization
CREATE OR REPLACE TABLE TOPIC_CLASSIFICATION (
    TOPIC_ID VARCHAR(50) PRIMARY KEY,
    COMPLAINT_ID VARCHAR(50) NOT NULL,
    PRIMARY_CATEGORY VARCHAR(100), -- network, billing, technical, service
    SUBCATEGORY VARCHAR(100),
    ROOT_CAUSE VARCHAR(200),
    KEYWORDS_DETECTED VARCHAR(1000), -- Comma-separated
    CLASSIFICATION_CONFIDENCE FLOAT, -- 0.0 to 1.0
    ANALYZED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'Topic classification and root cause detection';

-- CHURN_RISK_PREDICTION: ML model churn predictions
CREATE OR REPLACE TABLE CHURN_RISK_PREDICTION (
    PREDICTION_ID VARCHAR(50) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(50) UNIQUE NOT NULL,
    CHURN_PROBABILITY FLOAT, -- 0-100
    RISK_LEVEL VARCHAR(20), -- critical, high, medium, low
    RISK_FACTORS VARIANT, -- JSON array of contributing factors
    PREDICTION_DATE DATE NOT NULL,
    MODEL_VERSION VARCHAR(50),
    RECOMMENDED_ACTION TEXT,
    INTERVENTION_PRIORITY INT, -- 1-5
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'Churn risk predictions from ML model';

-- ALERT_TRIGGER: Critical issues flagged for immediate attention
CREATE OR REPLACE TABLE ALERT_TRIGGER (
    ALERT_ID VARCHAR(50) PRIMARY KEY,
    COMPLAINT_ID VARCHAR(50),
    CUSTOMER_ID VARCHAR(50),
    ALERT_TYPE VARCHAR(100), -- high_churn_risk, viral_social, vip_customer, repeated_issue
    SEVERITY VARCHAR(20), -- critical, high, medium
    ALERT_REASON TEXT,
    TRIGGERED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    ASSIGNED_TO VARCHAR(100),
    STATUS VARCHAR(20), -- new, acknowledged, in_progress, resolved
    ACKNOWLEDGED_TIMESTAMP TIMESTAMP_NTZ,
    RESOLUTION_TIMESTAMP TIMESTAMP_NTZ,
    RESOLUTION_NOTES TEXT,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'Real-time alerts for critical customer issues';

-- =====================================================================
-- SECTION 7: INTEGRATION SCHEMA - UC2 SYNCHRONIZATION
-- =====================================================================

USE SCHEMA INTEGRATION;

-- CUSTOMER_SITE_MAPPING: Customer to UC2 site assignments
CREATE OR REPLACE TABLE CUSTOMER_SITE_MAPPING (
    MAPPING_ID VARCHAR(50) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(50) NOT NULL,
    ACCOUNT_ID VARCHAR(50) NOT NULL,
    SITE_ID VARCHAR(50) NOT NULL, -- LINKS to UC2.DIM_CELL_SITE
    PRIMARY_SITE BOOLEAN DEFAULT FALSE,
    SERVICE_TYPES VARCHAR(100), -- mobile, home_internet, both
    COVERAGE_QUALITY VARCHAR(20), -- excellent, good, fair, poor
    DISTANCE_KM FLOAT,
    ASSIGNED_DATE DATE NOT NULL,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'Customer to UC2 network site mapping';

-- NETWORK_COMPLAINT_LINK: Correlation between UC2 incidents and complaints
CREATE OR REPLACE TABLE NETWORK_COMPLAINT_LINK (
    LINK_ID VARCHAR(50) PRIMARY KEY,
    INCIDENT_ID VARCHAR(50) NOT NULL, -- LINKS to UC2.FACT_INCIDENTS
    CASE_ID VARCHAR(50),
    COMPLAINT_ID VARCHAR(50) NOT NULL,
    CUSTOMER_ID VARCHAR(50) NOT NULL,
    INCIDENT_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    COMPLAINT_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    TIME_BETWEEN_INCIDENT_AND_COMPLAINT_MINUTES INT,
    COMPLAINT_MENTIONS_OUTAGE BOOLEAN DEFAULT FALSE,
    CORRELATION_CONFIDENCE INT, -- 0-100
    SITE_ID VARCHAR(50), -- LINKS to UC2.DIM_CELL_SITE
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'Links UC2 network incidents to customer complaints';

-- ROOT_CAUSE_ANALYSIS: Aggregated root cause insights
CREATE OR REPLACE TABLE ROOT_CAUSE_ANALYSIS (
    ANALYSIS_ID VARCHAR(50) PRIMARY KEY,
    ROOT_CAUSE_TYPE VARCHAR(50), -- network_incident, billing_issue, service_quality
    INCIDENT_ID VARCHAR(50), -- LINKS to UC2 if network-related
    DISPUTE_ID VARCHAR(50), -- LINKS to BILLING if billing-related
    AFFECTED_CUSTOMERS_COUNT INT,
    COMPLAINTS_RECEIVED_COUNT INT,
    AVG_SENTIMENT_SCORE FLOAT,
    TOTAL_REVENUE_AT_RISK DECIMAL(15,2),
    ANALYSIS_DATE DATE NOT NULL,
    ANALYSIS_PERIOD_START DATE,
    ANALYSIS_PERIOD_END DATE,
    DETAILS VARIANT, -- JSON with detailed analysis
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'Aggregated root cause analysis';

-- CUSTOMER_IMPACT_SCORE: Combined health metrics
CREATE OR REPLACE TABLE CUSTOMER_IMPACT_SCORE (
    SCORE_ID VARCHAR(50) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(50) UNIQUE NOT NULL,
    NETWORK_QUALITY_SCORE INT, -- 0-100, from UC2
    COMPLAINT_FREQUENCY_SCORE INT, -- 0-100
    SENTIMENT_TREND_SCORE INT, -- 0-100
    BILLING_DISPUTE_SCORE INT, -- 0-100
    PAYMENT_BEHAVIOR_SCORE INT, -- 0-100
    OVERALL_HEALTH_SCORE INT, -- 0-100, weighted average
    CHURN_RISK_FLAG BOOLEAN,
    CALCULATION_DATE DATE NOT NULL,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'Customer health score combining network, complaints, billing';

-- =====================================================================
-- SECTION 8: SUCCESS MESSAGE
-- =====================================================================

SELECT 'UC3 CUSTOMER COMPLAINTS database setup completed successfully!' as STATUS,
       'Database: UC3_CUSTOMER_COMPLAINTS' as DATABASE_NAME,
       '7 Schemas created' as SCHEMAS,
       '34 Tables created' as TABLES,
       'Ready for data loading' as NEXT_STEP;

SELECT 'Execute data generation scripts next to create CSV files' as INSTRUCTION;

