-- =====================================================================
-- DATA GENERATION VALIDATION SCRIPT
-- This script validates that all data has been generated successfully
-- across all schemas and tables
-- =====================================================================

-- Set context
USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE UC3_CUSTOMER_COMPLAINTS;

SELECT '========================================' as SECTION;
SELECT 'CUSTOMER DATA' as SECTION;
SELECT '========================================' as SECTION;

-- CUSTOMER_DATA Schema Tables
SELECT 'CUSTOMER_DATA.ACCOUNT' as TABLE_NAME, COUNT(*) as RECORD_COUNT, MIN(CREATED_DATE) as MIN_DATE, MAX(CREATED_DATE) as MAX_DATE FROM UC3_CUSTOMER_COMPLAINTS.CUSTOMER_DATA.ACCOUNT
UNION ALL
SELECT 'CUSTOMER_DATA.CONTACT', COUNT(*), MIN(CREATED_DATE), MAX(CREATED_DATE) FROM UC3_CUSTOMER_COMPLAINTS.CUSTOMER_DATA.CONTACT
UNION ALL
SELECT 'CUSTOMER_DATA.CASE', COUNT(*), MIN(CREATED_DATE), MAX(CREATED_DATE) FROM UC3_CUSTOMER_COMPLAINTS.CUSTOMER_DATA.CASE
UNION ALL
SELECT 'CUSTOMER_DATA.CASE_COMMENT', COUNT(*), MIN(CREATED_DATE), MAX(CREATED_DATE) FROM UC3_CUSTOMER_COMPLAINTS.CUSTOMER_DATA.CASE_COMMENT
UNION ALL
SELECT 'CUSTOMER_DATA.ASSET', COUNT(*), MIN(CREATED_DATE), MAX(CREATED_DATE) FROM UC3_CUSTOMER_COMPLAINTS.CUSTOMER_DATA.ASSET
UNION ALL
SELECT 'CUSTOMER_DATA.SERVICE_CONTRACT', COUNT(*), MIN(START_DATE), MAX(START_DATE) FROM UC3_CUSTOMER_COMPLAINTS.CUSTOMER_DATA.SERVICE_CONTRACT
ORDER BY TABLE_NAME;

SELECT '========================================' as SECTION;
SELECT 'BILLING DATA' as SECTION;
SELECT '========================================' as SECTION;

-- BILLING_DATA Schema Tables
SELECT 'BILLING_DATA.CUSTOMER_MASTER' as TABLE_NAME, COUNT(*) as RECORD_COUNT, MIN(CREATED_DATE) as MIN_DATE, MAX(CREATED_DATE) as MAX_DATE FROM UC3_CUSTOMER_COMPLAINTS.BILLING_DATA.CUSTOMER_MASTER
UNION ALL
SELECT 'BILLING_DATA.BILLING_ACCOUNT', COUNT(*), MIN(CREATED_DATE), MAX(CREATED_DATE) FROM UC3_CUSTOMER_COMPLAINTS.BILLING_DATA.BILLING_ACCOUNT
UNION ALL
SELECT 'BILLING_DATA.SUBSCRIPTION', COUNT(*), MIN(CREATED_DATE), MAX(CREATED_DATE) FROM UC3_CUSTOMER_COMPLAINTS.BILLING_DATA.SUBSCRIPTION
UNION ALL
SELECT 'BILLING_DATA.BILL_INVOICE', COUNT(*), MIN(INVOICE_DATE), MAX(INVOICE_DATE) FROM UC3_CUSTOMER_COMPLAINTS.BILLING_DATA.BILL_INVOICE
UNION ALL
SELECT 'BILLING_DATA.BILL_INVOICE_DETAIL', COUNT(*), MIN(CREATED_DATE), MAX(CREATED_DATE) FROM UC3_CUSTOMER_COMPLAINTS.BILLING_DATA.BILL_INVOICE_DETAIL
UNION ALL
SELECT 'BILLING_DATA.RATED_EVENTS', COUNT(*), MIN(EVENT_TIMESTAMP), MAX(EVENT_TIMESTAMP) FROM UC3_CUSTOMER_COMPLAINTS.BILLING_DATA.RATED_EVENTS
UNION ALL
SELECT 'BILLING_DATA.PAYMENT', COUNT(*), MIN(PAYMENT_DATE), MAX(PAYMENT_DATE) FROM UC3_CUSTOMER_COMPLAINTS.BILLING_DATA.PAYMENT
UNION ALL
SELECT 'BILLING_DATA.DISPUTE', COUNT(*), MIN(CREATED_DATE), MAX(CREATED_DATE) FROM UC3_CUSTOMER_COMPLAINTS.BILLING_DATA.DISPUTE
UNION ALL
SELECT 'BILLING_DATA.ADJUSTMENT', COUNT(*), MIN(APPLIED_DATE), MAX(APPLIED_DATE) FROM UC3_CUSTOMER_COMPLAINTS.BILLING_DATA.ADJUSTMENT
ORDER BY TABLE_NAME;

SELECT '========================================' as SECTION;
SELECT 'COMPLAINT DATA' as SECTION;
SELECT '========================================' as SECTION;

-- COMPLAINTS Schema Tables
SELECT 'COMPLAINTS.VOICE_TRANSCRIPT' as TABLE_NAME, COUNT(*) as RECORD_COUNT, MIN(CREATED_DATE) as MIN_DATE, MAX(CREATED_DATE) as MAX_DATE FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.VOICE_TRANSCRIPT
UNION ALL
SELECT 'COMPLAINTS.EMAIL_COMPLAINT', COUNT(*), MIN(CREATED_DATE), MAX(CREATED_DATE) FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.EMAIL_COMPLAINT
UNION ALL
SELECT 'COMPLAINTS.SOCIAL_MEDIA_POST', COUNT(*), MIN(CREATED_DATE), MAX(CREATED_DATE) FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.SOCIAL_MEDIA_POST
UNION ALL
SELECT 'COMPLAINTS.CHAT_SESSION', COUNT(*), MIN(CREATED_DATE), MAX(CREATED_DATE) FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.CHAT_SESSION
UNION ALL
SELECT 'COMPLAINTS.SURVEY_RESPONSE', COUNT(*), MIN(CREATED_DATE), MAX(CREATED_DATE) FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.SURVEY_RESPONSE
UNION ALL
SELECT 'COMPLAINTS.UNIFIED_COMPLAINT', COUNT(*), MIN(CREATED_DATE), MAX(CREATED_DATE) FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.UNIFIED_COMPLAINT
ORDER BY TABLE_NAME;

SELECT '========================================' as SECTION;
SELECT 'EXPECTED RECORD COUNTS' as SECTION;
SELECT '========================================' as SECTION;

SELECT 
    'Expected Counts' as INFO,
    '50,000 Accounts' as CUSTOMER,
    '300,000 Invoices' as BILLING,
    '1,000 Voice' as VOICE,
    '5,000 Emails' as EMAIL,
    '3,000 Social' as SOCIAL,
    '8,000 Chat' as CHAT,
    '12,000 Surveys' as SURVEY;

SELECT '========================================' as SECTION;
SELECT 'DATA QUALITY CHECKS' as SECTION;
SELECT '========================================' as SECTION;

-- Check for orphaned records in UNIFIED_COMPLAINT
SELECT 'Unified Complaints by Channel' as CHECK_NAME, CHANNEL, COUNT(*) as COUNT 
FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.UNIFIED_COMPLAINT 
GROUP BY CHANNEL
ORDER BY CHANNEL;

-- Check for NULL customer IDs
SELECT 'NULL Customer IDs in Voice Transcripts' as CHECK_NAME, COUNT(*) as COUNT 
FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.VOICE_TRANSCRIPT 
WHERE CUSTOMER_ID IS NULL;

SELECT 'NULL Customer IDs in Email Complaints' as CHECK_NAME, COUNT(*) as COUNT 
FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.EMAIL_COMPLAINT 
WHERE CUSTOMER_ID IS NULL;

SELECT 'NULL Customer IDs in Chat Sessions' as CHECK_NAME, COUNT(*) as COUNT 
FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.CHAT_SESSION 
WHERE CUSTOMER_ID IS NULL;

SELECT 'NULL Customer IDs in Social Media Posts' as CHECK_NAME, COUNT(*) as COUNT 
FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.SOCIAL_MEDIA_POST 
WHERE CUSTOMER_ID IS NULL;

SELECT 'NULL Customer IDs in Survey Responses' as CHECK_NAME, COUNT(*) as COUNT 
FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.SURVEY_RESPONSE 
WHERE CUSTOMER_ID IS NULL;

SELECT '========================================' as SECTION;
SELECT 'CUSTOMER LINKAGE VALIDATION' as SECTION;
SELECT '========================================' as SECTION;

-- Verify customers exist in master table
SELECT 'Voice Transcripts with Invalid Customer IDs' as CHECK_NAME, COUNT(*) as COUNT
FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.VOICE_TRANSCRIPT vt
WHERE NOT EXISTS (
    SELECT 1 FROM UC3_CUSTOMER_COMPLAINTS.BILLING_DATA.CUSTOMER_MASTER cm 
    WHERE cm.CUSTOMER_ID = vt.CUSTOMER_ID
);

SELECT 'Email Complaints with Invalid Customer IDs' as CHECK_NAME, COUNT(*) as COUNT
FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.EMAIL_COMPLAINT ec
WHERE NOT EXISTS (
    SELECT 1 FROM UC3_CUSTOMER_COMPLAINTS.BILLING_DATA.CUSTOMER_MASTER cm 
    WHERE cm.CUSTOMER_ID = ec.CUSTOMER_ID
);

SELECT 'Chat Sessions with Invalid Customer IDs' as CHECK_NAME, COUNT(*) as COUNT
FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.CHAT_SESSION cs
WHERE NOT EXISTS (
    SELECT 1 FROM UC3_CUSTOMER_COMPLAINTS.BILLING_DATA.CUSTOMER_MASTER cm 
    WHERE cm.CUSTOMER_ID = cs.CUSTOMER_ID
);

SELECT 'Social Media Posts with Invalid Customer IDs' as CHECK_NAME, COUNT(*) as COUNT
FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.SOCIAL_MEDIA_POST smp
WHERE NOT EXISTS (
    SELECT 1 FROM UC3_CUSTOMER_COMPLAINTS.BILLING_DATA.CUSTOMER_MASTER cm 
    WHERE cm.CUSTOMER_ID = smp.CUSTOMER_ID
);

SELECT 'Survey Responses with Invalid Customer IDs' as CHECK_NAME, COUNT(*) as COUNT
FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.SURVEY_RESPONSE sr
WHERE NOT EXISTS (
    SELECT 1 FROM UC3_CUSTOMER_COMPLAINTS.BILLING_DATA.CUSTOMER_MASTER cm 
    WHERE cm.CUSTOMER_ID = sr.CUSTOMER_ID
);

SELECT '========================================' as SECTION;
SELECT 'NETWORK INCIDENT LINKAGE' as SECTION;
SELECT '========================================' as SECTION;

-- Check network incident linkages
SELECT 'Voice Transcripts with Network Incidents' as CHECK_NAME, 
       COUNT(*) as TOTAL,
       SUM(CASE WHEN NETWORK_INCIDENT_ID IS NOT NULL THEN 1 ELSE 0 END) as WITH_INCIDENT,
       SUM(CASE WHEN NETWORK_INCIDENT_ID IS NULL THEN 1 ELSE 0 END) as WITHOUT_INCIDENT
FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.VOICE_TRANSCRIPT;

SELECT 'Unified Complaints with Network Incidents' as CHECK_NAME,
       COUNT(*) as TOTAL,
       SUM(CASE WHEN NETWORK_INCIDENT_ID IS NOT NULL THEN 1 ELSE 0 END) as WITH_INCIDENT,
       SUM(CASE WHEN NETWORK_INCIDENT_ID IS NULL THEN 1 ELSE 0 END) as WITHOUT_INCIDENT
FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.UNIFIED_COMPLAINT;

SELECT '========================================' as SECTION;
SELECT 'DATE RANGE VALIDATION' as SECTION;
SELECT '========================================' as SECTION;

-- Check data freshness (all should be recent)
SELECT 
    'Voice Transcripts' as TABLE_NAME,
    MIN(CALL_TIMESTAMP) as EARLIEST_RECORD,
    MAX(CALL_TIMESTAMP) as LATEST_RECORD,
    DATEDIFF(day, MIN(CALL_TIMESTAMP), MAX(CALL_TIMESTAMP)) as DATE_SPAN_DAYS
FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.VOICE_TRANSCRIPT
UNION ALL
SELECT 
    'Email Complaints',
    MIN(RECEIVED_TIMESTAMP),
    MAX(RECEIVED_TIMESTAMP),
    DATEDIFF(day, MIN(RECEIVED_TIMESTAMP), MAX(RECEIVED_TIMESTAMP))
FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.EMAIL_COMPLAINT
UNION ALL
SELECT 
    'Social Media Posts',
    MIN(POST_TIMESTAMP),
    MAX(POST_TIMESTAMP),
    DATEDIFF(day, MIN(POST_TIMESTAMP), MAX(POST_TIMESTAMP))
FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.SOCIAL_MEDIA_POST
UNION ALL
SELECT 
    'Chat Sessions',
    MIN(START_TIMESTAMP),
    MAX(START_TIMESTAMP),
    DATEDIFF(day, MIN(START_TIMESTAMP), MAX(START_TIMESTAMP))
FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.CHAT_SESSION
UNION ALL
SELECT 
    'Survey Responses',
    MIN(RESPONSE_TIMESTAMP),
    MAX(RESPONSE_TIMESTAMP),
    DATEDIFF(day, MIN(RESPONSE_TIMESTAMP), MAX(RESPONSE_TIMESTAMP))
FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.SURVEY_RESPONSE;

SELECT '========================================' as SECTION;
SELECT 'SAMPLE DATA PREVIEW' as SECTION;
SELECT '========================================' as SECTION;

-- Sample records from each complaint type
SELECT 'Sample Voice Transcript' as TYPE, CALL_ID, CUSTOMER_ID, CALL_TIMESTAMP, SUBSTR(TRANSCRIPT_TEXT, 1, 100) as SAMPLE_TEXT
FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.VOICE_TRANSCRIPT
LIMIT 3;

SELECT 'Sample Email Complaint' as TYPE, EMAIL_ID, CUSTOMER_ID, RECEIVED_TIMESTAMP, SUBSTR(SUBJECT, 1, 100) as SAMPLE_TEXT
FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.EMAIL_COMPLAINT
LIMIT 3;

SELECT 'Sample Social Media Post' as TYPE, POST_ID, CUSTOMER_ID, POST_TIMESTAMP, SUBSTR(POST_TEXT, 1, 100) as SAMPLE_TEXT
FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.SOCIAL_MEDIA_POST
LIMIT 3;

SELECT 'Sample Chat Session' as TYPE, SESSION_ID, CUSTOMER_ID, START_TIMESTAMP, SUBSTR(TRANSCRIPT_TEXT, 1, 100) as SAMPLE_TEXT
FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.CHAT_SESSION
LIMIT 3;

SELECT 'Sample Survey Response' as TYPE, RESPONSE_ID, CUSTOMER_ID, RESPONSE_TIMESTAMP, SUBSTR(COMMENT_TEXT, 1, 100) as SAMPLE_TEXT
FROM UC3_CUSTOMER_COMPLAINTS.COMPLAINTS.SURVEY_RESPONSE
WHERE COMMENT_TEXT IS NOT NULL
LIMIT 3;

SELECT '========================================' as SECTION;
SELECT 'VALIDATION COMPLETE!' as SECTION;
SELECT '========================================' as SECTION;

SELECT 
    'Validation Summary' as SUMMARY,
    'Check above sections for:' as INSTRUCTIONS,
    '1. Record counts match expected values' as CHECK_1,
    '2. All quality checks show 0 invalid records' as CHECK_2,
    '3. Date ranges are reasonable' as CHECK_3,
    '4. Sample data looks correct' as CHECK_4;
